### ISSUE TITLE
Réussir à écrire une donnée dans la database à partir d'un endpoint API (Spring Boot)

### ISSUE THREAD

**Issue by ChaoticEmergence** [ChaoticEmergence/projeux#12]

**Comment by leye0** [comment]
Ex: https://www.codejava.net/frameworks/spring-boot/spring-boot-spring-data-jpa-mysql-example

**Comment by ChaoticEmergence** [comment]
La table se génère comme c'est supposé mais les opérations CRUD ne fonctionnent pas.

**Comment by ChaoticEmergence** [comment]
C'est bon le problème venait de Spring Security qui redirigeait toutes les requêtes à une login page. J'ai exclu la classe SecurityAutoConfiguration de @SpringBootApplication et ça fonctionne.

@SpringBootApplication(exclude = {
		org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration.class}
)
