### ISSUE TITLE
Trouver un hosting

### ISSUE THREAD

**Issue by ChaoticEmergence** [ChaoticEmergence/projeux#15]
Idées ici:
https://www.reddit.com/r/SpringBoot/comments/zbcm1w/where_do_you_host_spring_boot_apps/

Hetzner et Digital Ocean sont souvent mentionnés.

On pourrait prendre une solution Cloud (au lieu d'un dedicated server) vu qu'on veut simplement des endpoints, une petite database et de l'authentication (et un site client hosted). J'ai vu qu'il existe une dependency "Spring Cloud Connector" qui permet d'avoir du code (ou un stack technologique dans notre app) optimisé pour rouler sur du Cloud.

Linode est vraiment le meilleur sur tous les aspects, mais plus cher pour le forfait minimum.

Hetzner est définitivement le moins cher. Il y a un forfait assez intéressant autour de 10 ou 12$ par mois.

https://www.reddit.com/r/hetzner/comments/vvozkh/hezner_vs_digitalocean_in_2022/
https://blog.nexxwave.be/benchmark-tussen-digitalocean-linode-vultr-ovh-en-hetzner-vpss/

La latency peut quand même être un facteur important pour l'échange de data entre le client et le serveur, et pour l'échange de données entre les joueurs.

**Comment by leye0** [comment]
Linode est vraiment le meilleur.

Mais Hetzner est définitivement le moins cher.

**Comment by leye0** [comment]
J'ai pris un abonnement à un Cloud server chez Hetzner.
