### ISSUE TITLE
Trouver 3-4 screenshots de jeux avec une apparence similaire

### ISSUE THREAD

**Issue by ChaoticEmergence** [ChaoticEmergence/projeux#2]
Objectif: Venir coller ici 3-4 screenshots

**Comment by ChaoticEmergence** [comment]
![Image](https://user-images.githubusercontent.com/90012643/213072242-05fe7c08-2dc7-47eb-831e-ce6d41294c25.jpg)

**Comment by ChaoticEmergence** [comment]
![Image](https://user-images.githubusercontent.com/90012643/213342104-17889d4e-3b34-4e64-82c1-848c1747725d.jpg)

**Comment by ChaoticEmergence** [comment]
![Image](https://user-images.githubusercontent.com/90012643/213342130-32fe154f-a992-4113-afb4-e73717ae5009.jpg)

**Comment by ChaoticEmergence** [comment]
![Image](https://user-images.githubusercontent.com/90012643/213342165-c221dcd8-e9eb-4fe7-8346-9bbd0b3d97b3.jpg)

**Comment by leye0** [comment]
NICE, le dernier est Boulderdash, je jouais sur Atari 65XE. <3
